In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [5]:
data = pd.read_csv('1.01.+Simple+linear+regression (2).csv')
data.head() #View first 5 rows

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [6]:
x = data['SAT']
y = data['GPA']

In [7]:
x.shape

(84,)

In [8]:
y.shape

(84,)

In [23]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [24]:
reg = LinearRegression()
reg.fit(x_matrix,y)

LinearRegression()

In [13]:
reg.score(x_matrix,y)

0.40600391479679765

In [15]:
reg.coef_

array([0.00165569])

In [18]:
reg.intercept_

0.2750402996602803

In [28]:
reg.predict([[1203]]) # We trained the model as a 2D so scikit learn expects a 2D array, that's the reason of the brackets

array([2.26683302])

In [56]:
new_data = pd.DataFrame(data = [[1203],[1740]],columns = ['SAT'])
new_data

SAT
0  1203
1  1740

In [60]:
reg.predict(new_data[['SAT']])

C:\Anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([2.26683302, 3.15593751])

In [58]:
new_data['Predicted GPA'] = reg.predict(new_data[['SAT']])
new_data

C:\Anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  Predicted GPA
0  1203       2.266833
1  1740       3.155938